// Conference Data Structure
const conferencesData = {
    "upcoming": [
        { img: "next.png", alt: "Next Talks", url: null },
        { img: "a4q.png", alt: "Testing Summit", url: null },
        { img: "ucaatLogo.jpg", alt: "UCAAT ", url: null }
    ],
    "2026": [
        { img: "2026.png", alt: "2026 Conferences", url: null }
    ],
    
    "2025": [
        { img: "2025.png", alt: "2025 Conferences", url: null },
        { img: "ttf.png", alt: "Tokyo Test Fest", url: null },
        { img: "kwsqa.png", alt: "KWSQA Conference", url: null },
        { img: "softcon.png", alt: "SoftCon", url: null },
        { img: "hustefLogo.png", alt: "Hustef Conference", url: null },
        { img: "pnsqc.jpg", alt: "PNSQC Conference", url: null },
        { img: "handson.png", alt: "Hands-On Conference", url: "https://www.youtube.com/live/XaFqLMkMHpM" },
        { img: "kcdc.png", alt: "KCDC Conference", url: null },
        { img: "sparks.jpg", alt: "Sparks Conference", url: null },
        { img: "atd.png", alt: "ATD Conference", url: "https://youtu.be/lWlfRO4Fu9E" },
        { img: "a4q.png", alt: "A4Q Conference", url: "https://www.youtube.com/live/6SL_Js-JmzY" },
        { img: "cityjs.jpg", alt: "CityJS Conference", url: "https://youtu.be/4jQJ_R48VaU" },
        { img: "live2test.jpg", alt: "Live2Test Conference", url: null },
        { img: "stf.png", alt: "STF Conference", url: null },
        { img: "ndc.png", alt: "NDC Conference", url: "https://youtu.be/vXsO7YlflO0" },
        { img: "gsdc.png", alt: "GSDC Conference", url: null },
        { img: "jotb.jpg", alt: "JOTB Conference", url: "https://youtu.be/pvXyuuCZENc" },
        { img: "maythefourth.jpg", alt: "May the Fourth Conference", url: null },
        { img: "niigata.png", alt: "Niigata Conference", url: null },
        { img: "jasst.png", alt: "JaSST Conference", url: null },
        { img: "prod.png", alt: "Product Conference", url: "https://gitnation.com/contents/can-machines-learn-bug-language" },
        { img: "witd.png", alt: "WITD Conference", url: null },
        { img: "rsgt.jpg", alt: "RSGT Conference", url: "https://youtu.be/A7lPTnUPiXI" },
        { img: "conf42.png", alt: "Conf42", url: "https://youtu.be/fyx3x6MX7SU" }
    ],
    
    "2024": [
        { img: "2024.png", alt: "2024 Conferences", url: null },
        { img: "yava.png", alt: "YAVA Conference", url: null },
        { img: "festive.png", alt: "Festive Tech Conference", url: "https://youtu.be/d08CkYwE_1Q" },
        { img: "jsconfjp.png", alt: "JSConf JP", url: "https://youtu.be/s_iJA5WEe2Y" },
        { img: "testconeu.png", alt: "TestCon Europe", url: null },
        { img: "testflix.png", alt: "Testflix", url: "https://youtu.be/b1B5EubjNVM" },
        { img: "softcon.png", alt: "SoftCon", url: null },
        { img: "addo.png", alt: "ADDO Conference", url: null },
        { img: "handson.png", alt: "Hands-On Conference", url: "https://youtu.be/jtSKwIp9GZE" },
        { img: "testmu.jpg", alt: "TestMu Conference", url: "https://youtu.be/cnfHKyJgWEg" },
        { img: "kcdc.png", alt: "KCDC Conference", url: null },
        { img: "mstech.png", alt: "MS Tech Conference", url: null },
        { img: "developerweekeurope.png", alt: "Developer Week Europe", url: null },
        { img: "devopspro.png", alt: "DevOps Pro", url: null },
        { img: "ittage23.png", alt: "IT Tage 2023", url: null },
        { img: "maythefourth.jpg", alt: "May the Fourth Conference", url: null },
        { img: "witd.png", alt: "WITD Conference", url: null },
        { img: "jasst.png", alt: "JaSST Conference", url: null },
        { img: "booster.jpg", alt: "Booster Conference", url: null },
        { img: "webhack.png", alt: "WebHack Conference", url: "content.html?category=conferences&id=webhack" },
        { img: "dw.jpg", alt: "Developer Week", url: null },
        { img: "worqference.png", alt: "Worqference", url: null },
        { img: "conf42.png", alt: "Conf42", url: "content.html?category=conferences&id=conf42" },
        { img: "mottokyo.png", alt: "MOT Tokyo", url: "content.html?category=conferences&id=mottokyo" },
        { img: "90days.png", alt: "90 Days of DevOps", url: "content.html?category=conferences&id=90days" }
    ],
    
    "2023": [
        { img: "2023.png", alt: "2023 Conferences", url: null },
        { img: "festive.png", alt: "Festive Tech Conference", url: "content.html?category=conferences&id=festive23" },
        { img: "testjs.png", alt: "TestJS Summit", url: null },
        { img: "devai.png", alt: "Dev AI Conference", url: null },
        { img: "yava.png", alt: "YAVA Conference", url: null },
        { img: "dss.png", alt: "DSS Conference", url: null },
        { img: "tas.png", alt: "TAS Conference", url: null },
        { img: "ucaatLogo.jpg", alt: "UCAAT Conference", url: null },
        { img: "atd.png", alt: "ATD Conference", url: null },
        { img: "addo.png", alt: "ADDO Conference", url: "content.html?category=conferences&id=addo23" },
        { img: "hustefLogo.png", alt: "Hustef Conference", url: "content.html?category=conferences&id=hustef23" },
        { img: "heisenbug.jpg", alt: "Heisenbug Conference", url: "content.html?category=conferences&id=heisenbug23-2" },
        { img: "qualitycon.png", alt: "QualityCon", url: null },
        { img: "stw.png", alt: "Software Testing World", url: null },
        { img: "pnsqc.jpg", alt: "PNSQC Conference", url: null },
        { img: "qstagLogo.jpeg", alt: "Q-STAG Conference", url: null },
        { img: "testflix.png", alt: "Testflix", url: "content.html?category=conferences&id=testflix23" },
        { img: "taipei.png", alt: "Taipei Conference", url: null },
        { img: "handson.png", alt: "Hands-On Conference", url: null },
        { img: "testmu.jpg", alt: "TestMu Conference", url: "content.html?category=conferences&id=testmu" },
        { img: "scottish.png", alt: "Scottish Summit", url: "content.html?category=conferences&id=scottish23" },
        { img: "stag.jpeg", alt: "STAG Conference", url: "content.html?category=conferences&id=stag" },
        { img: "maythefourth.jpg", alt: "May the Fourth Conference", url: "content.html?category=conferences&id=maythefourth" },
        { img: "sqd.png", alt: "SQD Conference", url: null },
        { img: "javadayist.jpg", alt: "Java Day Istanbul", url: "content.html?category=conferences&id=javadayist" },
        { img: "agilemanchester.png", alt: "Agile Manchester", url: null },
        { img: "bugraptors.png", alt: "BugRaptors Conference", url: "content.html?category=conferences&id=bugraptors" },
        { img: "skilup.jpeg", alt: "SkilUp Conference", url: "content.html?category=conferences&id=skilup" },
        { img: "inflectra.jpg", alt: "Inflectra Conference", url: "content.html?category=conferences&id=inflectra" },
        { img: "tokyo.png", alt: "Tokyo Conference", url: "content.html?category=conferences&id=tokyo23" },
        { img: "heisenbug.jpg", alt: "Heisenbug Conference", url: "content.html?category=conferences&id=heisenbug23" },
        { img: "witd.png", alt: "WITD Conference", url: "content.html?category=conferences&id=witd" },
        { img: "ittage365.png", alt: "IT Tage 365", url: "content.html?category=conferences&id=ittage365-23" },
        { img: "jasst.png", alt: "JaSST Conference", url: null },
        { img: "confoo.png", alt: "ConFoo Conference", url: null },
        { img: "dw.jpg", alt: "Developer Week", url: null },
        { img: "codegen.png", alt: "CodeGen Conference", url: "content.html?category=conferences&id=codegen" },
        { img: "breakfree.png", alt: "Break Free Conference", url: "content.html?category=conferences&id=breakfree" },
        { img: "jsworld.png", alt: "JS World Conference", url: "content.html?category=conferences&id=jsworld" }
    ],
    
    "2022": [
        { img: "2022.png", alt: "2022 Conferences", url: null },
        { img: "pnsqc.jpg", alt: "PNSQC Conference", url: "content.html?category=conferences&id=pnsqc" },
        { img: "developerweekeurope.png", alt: "Developer Week Europe", url: null },
        { img: "tsqa.jpg", alt: "TSQA Conference", url: "content.html?category=conferences&id=tsqa" },
        { img: "tokyo.png", alt: "Tokyo Conference", url: "content.html?category=conferences&id=tokyo22" },
        { img: "ankara22.jpg", alt: "Ankara Conference", url: "content.html?category=conferences&id=ankara22" },
        { img: "wearedevelopers.png", alt: "WeAreDevelopers", url: "content.html?category=conferences&id=wearedevelopers" },
        { img: "voxxedthes.jpg", alt: "Voxxed Thessaloniki", url: "content.html?category=conferences&id=voxxedthes" },
        { img: "agilille.png", alt: "Agile Lille", url: "content.html?category=conferences&id=agilille" },
        { img: "devweek21.jpg", alt: "Developer Week 2021", url: null },
        { img: "devconf.png", alt: "DevConf", url: null },
        { img: "palousa.png", alt: "Palousa", url: null },
        { img: "qasummit.png", alt: "QA Summit", url: null },
        { img: "handson.png", alt: "Hands-On Conference", url: "content.html?category=conferences&id=handson" },
        { img: "ucaatLogo.jpg", alt: "UCAAT Conference", url: "content.html?category=conferences&id=ucaat22" },
        { img: "agileindia.png", alt: "Agile India", url: "content.html?category=conferences&id=agileindia" },
        { img: "yava.png", alt: "YAVA Conference", url: "content.html?category=conferences&id=yava22" },
        { img: "qstagLogo.jpeg", alt: "Q-STAG Conference", url: null },
        { img: "testflix.png", alt: "Testflix", url: "content.html?category=conferences&id=testflix" },
        { img: "stf.png", alt: "STF Conference", url: null },
        { img: "pnsqc.jpg", alt: "PNSQC Conference", url: "content.html?category=conferences&id=pnsqc22" },
        { img: "festagiletr.png", alt: "Fest Agile TR", url: null },
        { img: "testconeu.png", alt: "TestCon Europe", url: "content.html?category=conferences&id=testcon22" },
        { img: "heisenbug.jpg", alt: "Heisenbug Conference", url: null },
        { img: "addo.png", alt: "ADDO Conference", url: "content.html?category=conferences&id=addo" },
        { img: "granite.png", alt: "Granite Conference", url: null },
        { img: "codeweek.jpg", alt: "Code Week", url: "content.html?category=conferences&id=codeweek" },
        { img: "ittage2022.png", alt: "IT Tage 2022", url: "content.html?category=conferences&id=ittage22" },
        { img: "festive.png", alt: "Festive Tech Conference", url: "content.html?category=conferences&id=festive" }
    ],
    
    "2021": [
        { img: "2021.png", alt: "2021 Conferences", url: null },
        { img: "ittage365.png", alt: "IT Tage 365", url: "content.html?category=conferences&id=ittage365" },
        { img: "scottish.png", alt: "Scottish Summit", url: "content.html?category=conferences&id=scottish" },
        { img: "aginextlogo.png", alt: "AgiNext Conference", url: "content.html?category=conferences&id=aginext" },
        { img: "tokyo.png", alt: "Tokyo Conference", url: "content.html?category=conferences&id=tokyo" },
        { img: "developerweekeurope.png", alt: "Developer Week Europe", url: "content.html?category=conferences&id=developerweekeurope" },
        { img: "otc.png", alt: "OTC Conference", url: "content.html?category=conferences&id=otc" },
        { img: "techorama.png", alt: "Techorama", url: "content.html?category=conferences&id=techorama" },
        { img: "qaday.png", alt: "QA Day", url: "content.html?category=conferences&id=qaday" },
        { img: "yava.png", alt: "YAVA Conference", url: "content.html?category=conferences&id=yava" },
        { img: "devweek21.jpg", alt: "Developer Week 2021", url: null },
        { img: "agile2021.png", alt: "Agile 2021", url: "content.html?category=conferences&id=agile2021" },
        { img: "tesinguy.png", alt: "Testing UY", url: "content.html?category=conferences&id=testinguy" },
        { img: "worldfestival.png", alt: "World Festival", url: null },
        { img: "palousa.png", alt: "Palousa", url: null },
        { img: "devconf.png", alt: "DevConf", url: "content.html?category=conferences&id=devconf" },
        { img: "spa.png", alt: "SPA Conference", url: null },
        { img: "festagile.png", alt: "Fest Agile", url: null },
        { img: "tesenalogo.png", alt: "Tesena Conference", url: null },
        { img: "ucaatLogo.jpg", alt: "UCAAT Conference", url: "content.html?category=conferences&id=ucaat2021" },
        { img: "hustefLogo.png", alt: "Hustef Conference", url: "content.html?category=conferences&id=hustef2021" },
        { img: "agilearizona.png", alt: "Agile Arizona", url: "content.html?category=conferences&id=agilearizona" },
        { img: "build.png", alt: "Build Conference", url: null },
        { img: "gtr.png", alt: "GTR Conference", url: "content.html?category=conferences&id=gtr" }
    ],
    
    "2020": [
        { img: "2020.png", alt: "2020 Conferences", url: null },
        { img: "tesenalogo.png", alt: "Tesena Conference", url: "content.html?category=conferences&id=tesena" },
        { img: "devopspro.png", alt: "DevOps Pro", url: "content.html?category=conferences&id=devopspro" },
        { img: "wfh.png", alt: "Work From Home", url: "content.html?category=conferences&id=wfh" },
        { img: "testingstagelogo.png", alt: "Testing Stage", url: "content.html?category=conferences&id=testingstage" },
        { img: "dataxdays.png", alt: "DataX Days", url: "content.html?category=conferences&id=dataxdays" },
        { img: "dw.jpg", alt: "Developer Week", url: "content.html?category=conferences&id=dw" },
        { img: "cloudouest.png", alt: "Cloud Ouest", url: "content.html?category=conferences&id=cloudouest" },
        { img: "devopsdaysist.png", alt: "DevOps Days Istanbul", url: "content.html?category=conferences&id=devopsdaysist" },
        { img: "rbi.jfif", alt: "RBI Conference", url: "content.html?category=conferences&id=rbi" },
        { img: "globalsummer.jfif", alt: "Global Summer", url: "content.html?category=conferences&id=globalsummer" },
        { img: "palousa.png", alt: "Palousa", url: "content.html?category=conferences&id=palousa" },
        { img: "globalai.png", alt: "Global AI", url: "content.html?category=conferences&id=globalai" },
        { img: "aadays.png", alt: "AA Days", url: "content.html?category=conferences&id=aadays" },
        { img: "devopscairo.jpg", alt: "DevOps Cairo", url: "content.html?category=conferences&id=devopscairo" },
        { img: "testcon.png", alt: "TestCon", url: "content.html?category=conferences&id=testcon" },
        { img: "testconeu.png", alt: "TestCon Europe", url: "content.html?category=conferences&id=testconeu" },
        { img: "qstagLogo.jpeg", alt: "Q-STAG Conference", url: "content.html?category=conferences&id=qstag" },
        { img: "ndc.png", alt: "NDC Sydney", url: "content.html?category=conferences&id=ndcsydney" },
        { img: "aidev.png", alt: "AI Dev", url: "content.html?category=conferences&id=aidev" },
        { img: "hustef2020Logo.png", alt: "Hustef 2020", url: "content.html?category=conferences&id=hustef2020" },
        { img: "devweekEnt.png", alt: "Developer Week Enterprise", url: "content.html?category=conferences&id=devweekEnt" },
        { img: "atd.png", alt: "ATD Conference", url: "content.html?category=conferences&id=atd" },
        { img: "buildstuff.png", alt: "Build Stuff", url: "content.html?category=conferences&id=buildstuff" },
        { img: "paristest.png", alt: "Paris Test", url: "content.html?category=conferences&id=paristest" },
        { img: "tesenalogo.png", alt: "Tesena Online", url: "content.html?category=conferences&id=tesenaonline" },
        { img: "ittage.png", alt: "IT Tage", url: "content.html?category=conferences&id=ittage" }
    ],
    
    "2019": [
        { img: "2019.png", alt: "2019 Conferences", url: null },
        { img: "ucaatLogo.jpg", alt: "UCAAT Conference", url: "content.html?category=conferences&id=ucaat" },
        { img: "qstagLogo.jpeg", alt: "SQS Conference", url: "content.html?category=conferences&id=sqs" },
        { img: "hustefLogo.png", alt: "Hustef Conference", url: "content.html?category=conferences&id=hustef" },
        { img: "iariaLogo.png", alt: "IARIA Conference", url: "content.html?category=conferences&id=valid" }
    ]
};

// Podcasts & Tech Talks Data
const podcastsData = [
    { img: "qacast.png", alt: "QA Cast Podcast", url: "https://youtu.be/uNQALqs3-0I" },
    { img: "qatts.jpg", alt: "QA TTS Podcast", url: "https://youtu.be/Xlc1SgET3uQ" },
    { img: "testeryou.png", alt: "Tester You Podcast", url: "https://youtu.be/uOY4ltHaCns" },
    { img: "ejable.jpg", alt: "Ejable Podcast", url: "https://youtu.be/DQMYLENe9gI" },
    { img: "creativeTech.png", alt: "Creative Tech Podcast", url: "https://youtu.be/b1JyNRocZGs" },
    { img: "richie.png", alt: "Richie's Podcast", url: "https://youtu.be/a_-1JILpLRI" },
    { img: "vitaly.jpg", alt: "Vitaly's Tech Talk", url: "https://youtu.be/5yd3IUJcgTk" },
    { img: "senor.jpg", alt: "Senor Testing", url: "https://www.youtube.com/live/qfv3tXgTcsM" }
];

// Interviews Data
const interviewsData = [
    { img: "agileindia.png", alt: "Agile India Interview", url: "https://confengine.com/conferences/agile-india-2022/speaker/interview/mesut-durukal?utm_source=twitter&utm_medium=organicsocial&utm_campaign=speakerinterviews" },
    { img: "mentorifi.jpg", alt: "Mentorifi Interview", url: "https://mentorifi.eventible.com/speakers-corner-featuring-mesut-durukal-quality-assurance-automation-engineer-indeed-com/" },
    { img: "infoq.png", alt: "InfoQ Interview", url: "https://www.infoq.com/news/2021/03/machine-learning-testing/?utm_campaign=infoq_content&utm_source=twitter&utm_medium=feed&utm_term=culture-methods" },
    { img: "bugraptors.png", alt: "BugRaptors Interview", url: "https://www.bugraptors.com/blog/tech-talks-with-mesut-durukal" },
    { img: "ejable.jpg", alt: "Ejable Interview", url: "https://www.ejable.com/interviews-with-engineers-in-japan/interview-with-mesut-durukal-of-indeed-japan/" },
    { img: "stw.png", alt: "Software Testing World Interview", url: "https://www.bigdataworldasia.com/show-news/ai-meets-software-testing-insights-indeeds-mesut-durukal" },
    { img: "tribe.png", alt: "Test Tribe Interview", url: "https://www.thetesttribe.com/blog/roadmap-playwright-tool/?" },
    { img: "creativeTech.png", alt: "Creative Tech Interview", url: "https://medium.com/@KaoreenRei/moving-to-tokyo-from-abroad-with-technology-skills-30-b0ba41a2ea3b" }
];

// Books & Contributions Data
const booksData = [
    { img: "amazon.png", alt: "Book on Amazon", url: "https://www.amazon.com/Searching-Website-Via-Spoken-Questions/dp/3846508144" },
    { img: "80testers.jfif", alt: "Around The World With 80 Software Testers", url: "https://leanpub.com/AroundTheWorldWith80SoftwareTesters" },
    { img: "80testersFromHome.jfif", alt: "Software People Work From Home", url: "https://leanpub.com/softwarepeopleworkfromhome" }
];

// Articles Data
const articlesData = [
    { img: "ieee.png", alt: "IEEE Article", url: "https://ieeexplore.ieee.org/document/7129820" },
    { img: "tm.gif", alt: "ThinkMind Article", url: "http://www.thinkmind.org/index.php?view=instance&instance=VALID+2019" },
    { img: "iiste.jpg", alt: "IISTE Article", url: "https://www.iiste.org/Journals/index.php/JSTR/article/view/23702/24273" },
    { img: "ij.png", alt: "IJSRCSEIT Article", url: "http://ijsrcseit.com/archive.php?v=5&i=28&pyear=2019" },
    { img: "agile2021.png", alt: "Agile Alliance Paper", url: "https://www.agilealliance.org/wp-content/uploads/2021/06/M.Durukal.Do-Bugs-Speak.pdf" },
    { img: "pnsqc.jpg", alt: "PNSQC Paper", url: "https://www.pnsqc.org/docs/PROP54426337-DurukalFinal_Camera-Ready.pdf" }
];

// Travel Data
const travelData = [
    { img: "icon_turkey.png", alt: "Turkey", url: "content.html?category=travel&id=turkey" },
    { img: "icon_ger.png", alt: "Germany", url: "content.html?category=travel&id=germany" },
    { img: "icon_bosnia.png", alt: "Bosnia", url: "content.html?category=travel&id=bosnia" },
    { img: "icon_croatia.png", alt: "Croatia", url: "content.html?category=travel&id=croatia" },
    { img: "icon_france.png", alt: "France", url: "content.html?category=travel&id=france" },
    { img: "icon_italy.png", alt: "Italy", url: "content.html?category=travel&id=italy" },
    { img: "icon_holland.png", alt: "Netherlands", url: "content.html?category=travel&id=holland" },
    { img: "icon_montenegro.png", alt: "Montenegro", url: "content.html?category=travel&id=montenegro" },
    { img: "icon_spain.png", alt: "Spain", url: "content.html?category=travel&id=spain" },
    { img: "icon_czech.png", alt: "Czech Republic", url: "content.html?category=travel&id=czech" },
    { img: "icon_hungary.png", alt: "Hungary", url: "content.html?category=travel&id=hungary" },
    { img: "icon_austria.png", alt: "Austria", url: "content.html?category=travel&id=austria" },
    { img: "icon_belgium.png", alt: "Belgium", url: "content.html?category=travel&id=belgium" },
    { img: "icon_portugal.png", alt: "Portugal", url: "content.html?category=travel&id=portugal" },
    { img: "icon-japan.jpg", alt: "Japan", url: "content.html?category=travel&id=japan" },
    { img: "icon_greece.png", alt: "Greece", url: "content.html?category=travel&id=greece" },
    { img: "icon_usa.png", alt: "United States", url: "content.html?category=travel&id=usa" },
    { img: "icon_canada.png", alt: "Canada", url: "content.html?category=travel&id=canada" },
    { img: "icon_england.png", alt: "England", url: "content.html?category=travel&id=england" },
    { img: "icon_singapore.png", alt: "Singapore", url: "content.html?category=travel&id=singapore" },
    { img: "icon_taiwan.png", alt: "Taiwan", url: "content.html?category=travel&id=taiwan" },
    { img: "icon_thai.png", alt: "Thailand", url: "content.html?category=travel&id=thailand" },
    { img: "icon_phi.png", alt: "Philippines", url: "content.html?category=travel&id=philiphines" },
    { img: "icon_vietnam.png", alt: "Vietnam", url: "content.html?category=travel&id=vietnam" },
    { img: "icon_denmark.png", alt: "Denmark", url: "content.html?category=travel&id=denmark" },
    { img: "icon_norway.png", alt: "Norway", url: "content.html?category=travel&id=norway" },
    { img: "icon_malaysia.png", alt: "Malaysia", url: "content.html?category=travel&id=malaysia" }
];
